version: '3.8'
services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev:latest
    container_name: shadowsocks-server
    ports:
      - "8388:8388/tcp"
      - "8388:8388/udp"
    environment:
      - METHOD=aes-256-gcm
      - PASSWORD=YourStrongPassword123
    restart: unless-stopped
    command: ss-server -s 0.0.0.0 \
                       -p 8388 \
                       -k YourStrongPassword123 \
                       -m aes-256-gcm \
                       -u
