version: '3.8'
services:
  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    container_name: shadowsocks-server
    ports:
      - "8388:8388/tcp"
      - "8388:8388/udp"
    environment:
      PASSWORD: YourStrongPassword123
      METHOD: aes-256-gcm
    restart: always
